safe: true
pygments: true
markdown: rdiscount
permalink: pretty
api:
  base_url: https://api.duet.me
  version: 1
resources:
  account:
    basic: |
      {
          "gender": null,
          "phone": "12121234567",
          "last_name": "Kuvalis",
          "image": "http://cdn.duet.me/default/account-image.png",
          "email": "account-5@email.com",
          "born_on": null,
          "first_name": "Zackery"
      }
    sign_in: |
      {
          "authentication_token": "rya3yxlxLwIF2OHVJBcX2F2e7gqDGzHxmT3v7eD3E0Lu35ox8FKwzXRSQdoz"
      }
    errors: |
      {
          "email": ["can't be blank"],
          "password": ["can't be blank"],
          "first_name": ["can't be blank"],
          "last_name": ["can't be blank"],
          "phone": ["can't be blank"]
      }
      