safe: true
pygments: true
markdown: rdiscount
permalink: pretty
api:
  base_url: https://api.duet.me
  version: 1
resources:
  account:
    basic: |
      {
          "id": 92,
          "gender": "m",
          "phone": "2998841598",
          "last_name": "Ledner",
          "image": {
              "large": "http://cdn.duet.me/default/large_account_image.png",
              "mini": "http://cdn.duet.me/default/mini_account_image.png",
              "medium": "http://cdn.duet.me/default/medium_account_image.png",
              "small": "http://cdn.duet.me/default/small_account_image.png"
          },
          "born_on": "1980-10-10",
          "email": "account-6@email.com",
          "first_name": "Merritt"
      }
    collection: |
      [
        {
            "id": 92,
            "gender": "m",
            "phone": "2998841598",
            "last_name": "Ledner",
            "image": {
                "large": "http://cdn.duet.me/default/large_account_image.png",
                "mini": "http://cdn.duet.me/default/mini_account_image.png",
                "medium": "http://cdn.duet.me/default/medium_account_image.png",
                "small": "http://cdn.duet.me/default/small_account_image.png"
            },
            "born_on": "1980-10-10",
            "email": "account-6@email.com",
            "first_name": "Merritt"
        }
        {
            "id": 27,
            "gender": "f",
            "phone": "3216549876",
            "last_name": "Williams",
            "image": {
                "large": "http://cdn.duet.me/default/large_account_image.png",
                "mini": "http://cdn.duet.me/default/mini_account_image.png",
                "medium": "http://cdn.duet.me/default/medium_account_image.png",
                "small": "http://cdn.duet.me/default/small_account_image.png"
            },
            "born_on": "1980-10-10",
            "email": "account-6@email.com",
            "first_name": "Merritt"
        }
      ]
    sign_in: |
      {
          "authentication_token": "rya3yxlxLwIF2OHVJBcX2F2e7gqDGzHxmT3v7eD3E0Lu35ox8FKwzXRSQdoz"
      }
    privacy: |
      {
        "promenade_sharing": false,
        "maximum_privacy": false
      }
    errors: |
      {
          "email": ["can't be blank"],
          "password": ["can't be blank"],
          "first_name": ["can't be blank"],
          "last_name": ["can't be blank"],
          "phone": ["can't be blank"]
      }
  duet:
    basic: |
      {
          "id": 92,
          "prefix": "Let's",
          "body": "bake a cake",
          "account_id": 14
      }
    collection: |
      [
        {
            "id": 92,
            "prefix": "Let's",
            "body": "bake a cake",
            "account_id": 14
        },
        {
            "id": 12,
            "prefix": "Let's",
            "body": "have a beer",
            "account_id": 14
        },
        {
            "id": 17,
            "prefix": "Let's",
            "body": "go run a race",
            "account_id": 14
        }
      ]
    errors: |
      {
          "body": ["can't be blank"],
      }
    public_collection: |
      [
        {
            "prefix": "Let's",
            "body": "bake a cake",
        },
        {
            "prefix": "Let's",
            "body": "have a beer",
        },
        {
            "prefix": "Let's",
            "body": "go run a race",
        }
      ]
  ditto:
    basic: |
      {
          "prefix": "Let's",
          "body": "bake a cake"
      }
    collection: |
      [
        {
            "prefix": "Let's",
            "body": "bake a cake"
        },
        {
            "prefix": "Let's",
            "body": "have a beer"
        },
        {
            "prefix": "Let's",
            "body": "go run a race"
        }
      ]
    errors: |
      {
          "duet_id": ["can't be blank"],
      }
