safe: true
pygments: true
markdown: rdiscount
permalink: pretty
api:
  base_url: https://api.duet.me
  version: 1
  resources:
    account:
      basic: |
          {
              "account" : {
                  "id": 92,
                  "phone": "2998841598",
                  "last_name": "Ledner",
                  "image": {
                    "large": "http://cdn.duet.me/uploads/account/image/22/large_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                    "medium": "http://cdn.duet.me/uploads/account/image/22/medium_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                    "full": "http://cdn.duet.me/uploads/account/image/22/full_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                    "medium@2x": "http://cdn.duet.me/uploads/account/image/22/medium2x_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                    "full@2x": "http://cdn.duet.me/uploads/account/image/22/full2x_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                    "large@2x": "http://cdn.duet.me/uploads/account/image/22/large2x_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                    "state": "current"
                  },
                  "email": "account-6@email.com",
                  "first_name": "Merritt"
              }
          }
      collection: |
        [
        {
            "account": {
                "image": {
                  "large": "http://cdn.duet.me/uploads/account/image/22/large_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "medium": "http://cdn.duet.me/uploads/account/image/22/medium_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "full": "http://cdn.duet.me/uploads/account/image/22/full_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "medium@2x": "http://cdn.duet.me/uploads/account/image/22/medium2x_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "full@2x": "http://cdn.duet.me/uploads/account/image/22/full2x_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "large@2x": "http://cdn.duet.me/uploads/account/image/22/large2x_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "state": "current"
                },
                "first_name": "Will",
                "last_name": "Ferrell",
                "phone": "9756457843",
                "email": "will@ferrell.com",
                "id": 1,
                "activity": 0
            }
        },
        {
            "account": {
                "image": {
                  "large": "http://cdn.duet.me/uploads/account/image/22/large_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "medium": "http://cdn.duet.me/uploads/account/image/22/medium_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "full": "http://cdn.duet.me/uploads/account/image/22/full_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "medium@2x": "http://cdn.duet.me/uploads/account/image/22/medium2x_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "full@2x": "http://cdn.duet.me/uploads/account/image/22/full2x_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "large@2x": "http://cdn.duet.me/uploads/account/image/22/large2x_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "state": "current"
                },
                "first_name": "Bill",
                "last_name": "Murray",
                "phone": "1231231234",
                "email": "bill@murray.com",
                "id": 2,
                "activity": 3
            }
        },
        {
            "account": {
                "image": {
                  "large": "http://cdn.duet.me/uploads/account/image/22/large_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "medium": "http://cdn.duet.me/uploads/account/image/22/medium_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "full": "http://cdn.duet.me/uploads/account/image/22/full_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "medium@2x": "http://cdn.duet.me/uploads/account/image/22/medium2x_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "full@2x": "http://cdn.duet.me/uploads/account/image/22/full2x_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "large@2x": "http://cdn.duet.me/uploads/account/image/22/large2x_e2512060-948c-012e-1bfb-4040900bc90c.jpg",
                  "state": "current"
                },
                "first_name": "Clint",
                "last_name": "Eastwood",
                "phone": "3231231234",
                "email": "clint@eastwood.com",
                "id": 3,
                "activity": null
            }
        }
        ]
      sign_in: |
        {
            "account": {
                "authentication_token": "rya3yxlxLwIF2OHVJBcX2F2e7gqDGzHxmT3v7eD3E0Lu35ox8FKwzXRSQdoz"
            }
        }
      privacy: |
        {
            "account": {
                "promenade_sharing": false,
                "maximum_privacy": false
            }
        }
      errors: |
        {
            "errors": {
                "email": ["can't be blank"],
                "password": ["can't be blank"],
                "first_name": ["can't be blank"],
                "last_name": ["can't be blank"],
                "phone": ["can't be blank"]
            }
        }
    duet:
      basic: |
        {
            "duet": {
                "id": 92,
                "proposed_by_id": 1,
                "prefix": "Let's",
                "body": "bake a cake",
                "video": "http://cdn.duet.me/uploads/duet/video/2/video.m4v",
                "state": "unpaired"
            }
        }
      active: |
        {
            "duet": {
                "id": 92,
                "prefix": "Let's",
                "body": "bake a cake",
                "video": "http://cdn.duet.me/uploads/duet/video/2/video.m4v",
                "state": "active"
                "proposed_by_id": 1,
                "proposed_to_id": 13
            }
        }
      proposed_to_phone_number: |
        {
            "duet": {
                "proposed_by_id": 1,
                "body": "watch a movie",
                "state": "proposed",
                "id": 1,
                "propose_to_phone_number": "1234567890",
                "prefix": "Let's"
            }
        }
      proposed_to_account: |
        {
            "duet": {
                "proposed_to_id": 2,
                "proposed_by_id": 1,
                "body": "watch a movie",
                "state": "proposed",
                "id": 1,
                "prefix": "Let's"
            }
        }
      collection: |
        [
        {
            "duet": {
                "id": 92,
                "proposed_by_id": 1,
                "prefix": "Let's",
                "body": "bake a cake",
                "state": "unpaired"
            }
        },
        {
            "duet": {
                "id": 12,
                "proposed_by_id": 1,
                "prefix": "Let's",
                "body": "have a beer",
                "video": "http://cdn.duet.me/uploads/duet/video/2/video.m4v",
                "state": "unpaired"
            }
        },
        {
            "duet": {
                "id": 17,
                "proposed_by_id": 1,
                "prefix": "Let's",
                "body": "go run a race",
                "state": "unpaired"
            }
        }
        ]
      errors: |
        {
            "errors": {
                "body": ["can't be blank"],
            }
        }
    item:
      basic: |
        {
            "item": {
                "created_at": "Tue, 19 Jul 2011 21:05:40 -0400",
                "content_type": "video",
                "created_by_id": 1,
                "id": 2,
                "video": "http://cdn.duet.me/uploads/item/video/2/4f188d50-949a-012e-ade3-001f5be78ffa.m4v",
                "message": "This is a test.",
                "image": {
                    "url": "http://cdn.duet.me/uploads/item/image/2/4f186f90-949a-012e-ade2-001f5be78ffa.png",
                    "height": 100,
                    "width": 100
                }
            }
        }
      collection: |
        [
        {
            "item": {
                "created_at": "Tue, 19 Jul 2011 21:05:40 -0400",
                "content_type": "video",
                "created_by_id": 1,
                "id": 2,
                "video": "http://cdn.duet.me/uploads/item/video/2/4f188d50-949a-012e-ade3-001f5be78ffa.m4v",
                "message": "This is a test.",
                "image": {
                    "url": "http://cdn.duet.me/uploads/item/image/2/4f186f90-949a-012e-ade2-001f5be78ffa.png",
                    "height": 100,
                    "width": 100
                }
            }
        },
        {
            "item": {
                "created_at": "Tue, 19 Jul 2011 21:05:40 -0400",
                "content_type": "image",
                "created_by_id": 1,
                "id": 34,
                "image": {
                    "url": "http://cdn.duet.me/uploads/item/image/2/4f186f90-949a-012e-ade2-001f5be78ffa.png",
                    "height": 100,
                    "width": 100
                }
            }
        },
        {
            "item": {
                "id": 22,
                "content_type": "message",
                "created_by_id": 3,
                "created_at": "Thu, 03 May 2011 09:09:12 -0400",
                "message": "That's such a good idea!"
            }
        }
        ]
      errors: |
        {
            "errors": {
                "message": ["can't be blank"],
            }
        }
