safe: true
pygments: true
markdown: rdiscount
permalink: pretty
api:
  base_url: https://api.duet.me
  version: 1
resources:
  account:
    basic: |
      {
          "id": 92,
          "gender": "m",
          "phone": "2998841598",
          "last_name": "Ledner",
          "image": {
              "large": "http://cdn.duet.me/default/large_account_image.png",
              "mini": "http://cdn.duet.me/default/mini_account_image.png",
              "medium": "http://cdn.duet.me/default/medium_account_image.png",
              "small": "http://cdn.duet.me/default/small_account_image.png"
          },
          "born_on": "1980-10-10",
          "email": "account-6@email.com",
          "first_name": "Merritt"
      }
    sign_in: |
      {
          "authentication_token": "rya3yxlxLwIF2OHVJBcX2F2e7gqDGzHxmT3v7eD3E0Lu35ox8FKwzXRSQdoz"
      }
    errors: |
      {
          "email": ["can't be blank"],
          "password": ["can't be blank"],
          "first_name": ["can't be blank"],
          "last_name": ["can't be blank"],
          "phone": ["can't be blank"]
      }
      